version: "3.9"
services:
  app:
    build: ./
    networks:
      - redis-net
    environment:
      BINANCE_API_KEY:
      BINANCE_API_SECRET:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - app-log:/logs
  redis:
    image: redis:6.2.0-alpine
    command: [ "redis-server", "--appendonly", "yes" ]
    hostname: redis
    networks:
      - redis-net
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

networks:
  redis-net:

volumes:
  redis-data:
  app-log: