version: "3.9"
services:
  app:
    build:
      dockerfile: ./src/main/docker/app/Dockerfile
      context: ./
    networks:
      - mrktmkr-net
    environment:
      BINANCE_API_KEY:
      BINANCE_API_SECRET:
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - "./logs:/logs"
    depends_on:
      - db
    restart: unless-stopped
  db:
    environment:
      POSTGRES_PASSWORD: secret
    networks:
      - mrktmkr-net
    build:
      dockerfile: ./Dockerfile
      context: ./src/main/docker/db/
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

networks:
  mrktmkr-net:
volumes:
  database-data: