spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://db:5432/mrktmkr
    username: mrktmkr
    password: secret
  flyway:
    enabled: true
  application:
    name: MrktMkr
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: WARN

    io.nkdtrdr.mrktmkr: WARN
    io.nkdtrdr.mrktmkr.disruptor: DEBUG
    io.nkdtrdr.mrktmkr.orders: DEBUG
symbol:
  base: DOGE
  quote: GBP
  minimum-order: 10.10
  order-price-adjustment: 0.00001
  base-scale: 1
  quote-scale: 5
binance:
  api-key: ${BINANCE_API_KEY}
  api-secret: ${BINANCE_API_SECRET}
strategy:
  limits:
    - strategy: BUY
      asset: GBP
      asset-cap: 20
    - strategy: SELL
      asset: DOGE
      asset-cap: 110
