spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://db:5432/mrktmkr
    username: mrktmkr
    password: secret
  flyway:
    enabled: true
  application:
    name: MrktMkr
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: WARN

    io.nkdtrdr.mrktmkr: WARN
symbol:
  base: BTC
  quote: GBP
  minimum-order: 10.10
  order-price-adjustment: 0.01
  base-scale: 6
  quote-scale: 2
binance:
  api-key: ${BINANCE_API_KEY}
  api-secret: ${BINANCE_API_SECRET}
strategy:
  limits:
    - strategy: BUY
      asset: GBP
      asset-cap: 35
    - strategy: SELL
      asset: BTC
      asset-cap: 0.001
